### PR TITLE
fix[#51]: Explicitly export types

### PR DESCRIPTION
**Pull request by codedhola**
fix types issues

### CODE REVIEW

**Review by E-wave112 — COMMENTED** [review]
This is super cool but i think you can go one abstraction lower

you should create a dedicated file in the `services` directly and export all the dtos there and then finally export the file itself in this `index.ts` file

**Comment by codedhola** [comment]
Noted, will fix up soon

**Comment by codedhola** [comment]
fixed, can you please review

**Review by E-wave112 — APPROVED** [review]
well done, will draft  a new release soon

**Pull request merged**
